# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: kyletru/container-structure:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout
      - setup_remote_docker

      - run: docker build . -t ${{REPO_NAME}}
      - run: container-structure-test test -c config.yaml -i ${{REPO_NAME}}

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master/
