# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: alpine
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout
      - setup_remote_docker

      - run: docker build . -t ${{REPO_NAME}}
      - run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test

      - run: container-structure-test test -c config.yaml -i ${{REPO_NAME}}

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master/
